### ISSUE TITLE
import java.util.*;  cannot access unnamed package in Java Notebook

### ISSUE THREAD

**Issue by joao-parana** [tabular-io/docker-spark-iceberg#43]
When I run the first cell in _**Iceberg - An Introduction to the Iceberg Java API**_ Notebook I get this error below:

```txt
|   import java.util.*;
cannot access unnamed package
  ZipException opening "tabular-client-runtime-0.28.2.jar": zip END header not found
```

I simply ran: `git clone ... ; cd docker-spark-iceberg ; docker-compose up`  and opened the notebook in http://localhost:8888/notebooks/Iceberg%20-%20An%20Introduction%20to%20the%20Iceberg%20Java%20API.ipynb 

In docker-compose Log appears the message:

```txt
docker-spark-iceberg-spark-iceberg-1  | error: error reading /opt/spark/jars/tabular-client-runtime-0.28.2.jar; zip END header not found
```

**Comment by joao-parana** [comment]
The cause of the error is this:

```bash
file  /opt/spark/jars/tabular-client-runtime-0.28.2.jar
/opt/spark/jars/tabular-client-runtime-0.28.2.jar: XML 1.0 document, ASCII text, with very long lines

cat  /opt/spark/jars/tabular-client-runtime-0.28.2.jar
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>releases/io/tabular/tabular-client-runtime/0.30.0-rc.11/tabular-client-runtime-0.28.2.jar</Key><RequestId>Q1S0JKZAGCMTJAFZ</RequestId><HostId>HtBchXXQfD0ouKvr4/wpMqo1lGoXEenPw3/Rfi4mM4aiBEwLsxNQtIf2B6sDBbZrm4HBMZ6jnOU=</HostId></Error>
```

**Comment by joao-parana** [comment]
I tried three approaches:

1 - remove all images and invoke `docker-compose up` command
2 - build the `tabulario/spark-iceberg:latest` image locally before running the `docker-compose up` command
3 - run `docker pull tabulario/spark-iceberg:latest` command before running `docker-compose up` command

In all cases the error remained the same.

**Comment by samredai** [comment]
@joao-parana thanks for opening this issue! @Fokko can you confirm the correct URL for the client runtime jar?

**Comment by creechy** [comment]
I think the URL for the runtime is stale. I changed lines 53-54 of `spark/Dockerfile` to
```
RUN curl https://tabular-repository-public.s3.amazonaws.com/releases/io/tabular/tabular-client-runtime/0.34.0-rc.3/tabular-client-runtime-0.34.0-rc.3.jar -Lo tabular-client-runtime-0.34.0-rc.3.jar \
 && mv tabular-client-runtime-0.34.0-rc.3.jar /opt/spark/jars
```
That seemed to fix it.

**Comment by joao-parana** [comment]
Hi @creechy, I changed Dockerfile in spark directory in `main` branch.

and ran :
```bash
docker-compose build 
docker-compose up
```
 
That error disappeared but now another error has occurred when I ran the first cell of **_Iceberg - An Introduction to the Iceberg Java API_** Notebook :

```txt
---------------------------------------------------------------------------
org.apache.iceberg.jdbc.UncheckedSQLException: Failed to connect: jdbc:postgresql://postgres:5432/demo_catalog
	at org.apache.iceberg.jdbc.JdbcClientPool.newClient(JdbcClientPool.java:53)
	at org.apache.iceberg.jdbc.JdbcClientPool.newClient(JdbcClientPool.java:31)
	at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:125)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:56)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
	at org.apache.iceberg.jdbc.JdbcCatalog.initializeCatalogTables(JdbcCatalog.java:118)
	at org.apache.iceberg.jdbc.JdbcCatalog.initialize(JdbcCatalog.java:103)
	at .(#27:1)
```


RUN curl https://tabular-repository-public.s3.amazonaws.com/releases/io/tabular/tabular-client-runtime/0.34.0-rc.3/tabular-client-runtime-0.34.0-rc.3.jar -Lo tabular-client-runtime-0.34.0-rc.3.jar \
&& mv tabular-client-runtime-0.34.0-rc.3.jar /opt/spark/jars \
&& file /opt/spark/jars/tabular-client-runtime-0.34.0-rc.3.jar > /tmp/tabular-file.txt \
&& cat /tmp/tabular-file.txt

**Comment by joao-parana** [comment]
See below the Java code in this cell:

```java
import org.apache.iceberg.catalog.Catalog;
import org.apache.hadoop.conf.Configuration;
import org.apache.iceberg.CatalogProperties;
import org.apache.iceberg.jdbc.JdbcCatalog;
import org.apache.iceberg.hadoop.HadoopFileIO;

Map<String, String> properties = new HashMap<>();

properties.put(CatalogProperties.CATALOG_IMPL, JdbcCatalog.class.getName());
properties.put(CatalogProperties.URI, "jdbc:postgresql://postgres:5432/demo_catalog");
properties.put(JdbcCatalog.PROPERTY_PREFIX + "user", "admin");
properties.put(JdbcCatalog.PROPERTY_PREFIX + "password", "password");
properties.put(CatalogProperties.WAREHOUSE_LOCATION, "/home/iceberg/warehouse");
properties.put(CatalogProperties.FILE_IO_IMPL, HadoopFileIO.class.getName());

JdbcCatalog catalog = new JdbcCatalog();
Configuration conf = new Configuration();
catalog.setConf(conf);
catalog.initialize("demo", properties);
catalog.name();
```

**Comment by joao-parana** [comment]
I made sure I'm on the `main` branch

```txt
soma in repo: docker-spark-iceberg on  main [!] took 13ms
✦  ╰─λ git branch
3.3.0_0.14.0
* main
```

**Comment by creechy** [comment]
Ya. That's basically the same `docker-compose.yml` that's in this article - https://tabular.io/blog/docker-spark-and-iceberg/. FWIW I added the `postgres` section to the `docker-compose.yml` in `main` locally and that was enough to get past your second problem.

**Comment by joao-parana** [comment]
Yes, I changed it here locally and it worked. Can you do `git commit` and `git push` these changes to the `docker-compose.yaml` and `Dockerfile` file?

**Comment by creechy** [comment]
I will work with @Fokko to figure out the correct path forward. It looks as though the intention is to get rid of the postgres dependency altogether.

**Comment by jake123456789ok** [comment]
I hope to synchronize the latest changes to the corresponding docker image, but I also encountered the problems you mentioned above, which caused the normal operation.

**Comment by jake123456789ok** [comment]
I hope to synchronize the latest changes to the corresponding docker image, but I also encountered the problems you mentioned above, which caused the normal operation.

**Comment by jake123456789ok** [comment]
I hope the maintainers can sync the latest fix changes to the corresponding docker image, because I am also experiencing the issues you mentioned above.
