### ISSUE TITLE
package errors compilation issue

### ISSUE THREAD

**Issue by RaoPisay** [tabular-io/docker-spark-iceberg#55]
classes FakerLORSource and LORSink are having wrong pakcage declaration i.e io.iceberg.flink.lor.example insead of io.tabular.flink.lor.example which is causing compilation errors while building.

**Comment by Fokko** [comment]
Thanks @RaoPisay for raising this issue. Happy to look into this, but do you have any steps to reproduce this?

**Comment by RaoPisay** [comment]
@Fokko, when I import the project I see the compilation issues, to repoduce just import the project.
