### ISSUE TITLE
Caused by: java.net.UnknownHostException: rest: Temporary failure in name resolution

### ISSUE THREAD

**Issue by ludlows** [tabular-io/docker-spark-iceberg#58]
hi, 

after running a %%sql cell in python notebook, I found the following errors:

> Py4JJavaError                             Traceback (most recent call last)
> Cell In[3], line 1
> ----> 1 spark.sql('DROP TABLE IF EXISTS nyc.taxis')
> 
> File /opt/spark/python/pyspark/sql/session.py:1034, in SparkSession.sql(self, sqlQuery, **kwargs)
>    1032     sqlQuery = formatter.format(sqlQuery, **kwargs)
>    1033 try:
> -> 1034     return DataFrame(self._jsparkSession.sql(sqlQuery), self)
>    1035 finally:
>    1036     if len(kwargs) > 0:
> 
> File /opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
>    1315 command = proto.CALL_COMMAND_NAME +\
>    1316     self.command_header +\
>    1317     args_command +\
>    1318     proto.END_COMMAND_PART
>    1320 answer = self.gateway_client.send_command(command)
> -> 1321 return_value = get_return_value(
>    1322     answer, self.gateway_client, self.target_id, self.name)
>    1324 for temp_arg in temp_args:
>    1325     temp_arg._detach()
> 
> File /opt/spark/python/pyspark/sql/utils.py:190, in capture_sql_exception.<locals>.deco(*a, **kw)
>     188 def deco(*a: Any, **kw: Any) -> Any:
>     189     try:
> --> 190         return f(*a, **kw)
>     191     except Py4JJavaError as e:
>     192         converted = convert_exception(e.java_exception)
> 
> File /opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
>     324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
>     325 if answer[1] == REFERENCE_TYPE:
> --> 326     raise Py4JJavaError(
>     327         "An error occurred while calling {0}{1}{2}.\n".
>     328         format(target_id, ".", name), value)
>     329 else:
>     330     raise Py4JError(
>     331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
>     332         format(target_id, ".", name, value))
> 
> Py4JJavaError: An error occurred while calling o36.sql.
> : org.apache.iceberg.exceptions.RESTException: Error occurred while processing GET request
> 	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:243)
> 	at org.apache.iceberg.rest.HTTPClient.get(HTTPClient.java:259)
> 	at org.apache.iceberg.rest.RESTSessionCatalog.fetchConfig(RESTSessionCatalog.java:765)
> 	at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:151)
> 	at org.apache.iceberg.rest.RESTCatalog.initialize(RESTCatalog.java:70)
> 	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:237)
> 	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:282)
> 	at org.apache.iceberg.spark.SparkCatalog.buildIcebergCatalog(SparkCatalog.java:129)
> 	at org.apache.iceberg.spark.SparkCatalog.initialize(SparkCatalog.java:519)
> 	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
> 	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$catalog$1(CatalogManager.scala:53)
> 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
> 	at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:53)
> 	at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:122)
> 	at org.apache.spark.sql.connector.catalog.LookupCatalog.currentCatalog(LookupCatalog.scala:34)
> 	at org.apache.spark.sql.connector.catalog.LookupCatalog.currentCatalog$(LookupCatalog.scala:34)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.currentCatalog(Analyzer.scala:187)
> 	at org.apache.spark.sql.connector.catalog.LookupCatalog$CatalogAndIdentifier$.unapply(LookupCatalog.scala:125)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$lookupTableOrView$2(Analyzer.scala:1128)
> 	at scala.Option.orElse(Option.scala:447)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupTableOrView(Analyzer.scala:1127)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$13.applyOrElse(Analyzer.scala:1085)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$13.applyOrElse(Analyzer.scala:1023)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:138)
> 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:134)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:130)
> 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:30)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$2(AnalysisHelper.scala:135)
> 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1228)
> 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1227)
> 	at org.apache.spark.sql.catalyst.plans.logical.DropTable.mapChildren(v2Commands.scala:661)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:135)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:134)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:130)
> 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:30)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:1023)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:982)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
> 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
> 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
> 	at scala.collection.immutable.List.foldLeft(List.scala:91)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
> 	at scala.collection.immutable.List.foreach(List.scala:431)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:227)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:223)
> 	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:172)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:223)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:187)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
> 	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:208)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
> 	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:207)
> 	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:76)
> 	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
> 	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
> 	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
> 	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:185)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
> 	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:184)
> 	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:76)
> 	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
> 	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
> 	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
> 	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
> 	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
> 	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
> 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.net.UnknownHostException: rest: Temporary failure in name resolution
> 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
> 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
> 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
> 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
> 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
> 	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
> 	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
> 	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
> 	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
> 	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
> 	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
> 	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
> 	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
> 	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
> 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
> 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
> 	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:212)
> 	... 87 more
> 
> 

does anyone know how to solve this problem?
many thanks.

**Comment by Fokko** [comment]
@ludlows I'm unable to reproduce this on my side. Could you check with the latest version if it still fails on your end? Many thanks!
