### ISSUE TITLE
iceberg-rest does not persist catalog after docker-compose down

### ISSUE THREAD

**Issue by dcarr178** [tabular-io/docker-spark-iceberg#77]
Everything works great for me when I docker-compose up with spark, iceberg-rest, and minio running in docker. I can use pyspark to create tables in the iceberg catalog and they get created in minio. I persist my minio /data volume so that I can docker-compose down and later docker-compose up and my minio buckets and objects are still there.

However, when I docker-compose down and then up, I can no longer query my iceberg tables because iceberg-rest returns a "Table does not exist" message even though the table still does exist in minio.

Does the iceberg catalog only exist in memory which is why it's gone after docker-compose down/up? Or does it get persisted to disk and if so, can you point me to what path so that I can add it as a local column in my docker-compose.yaml?

Thanks!

**Comment by dcarr178** [comment]
Alternatively, if the iceberg catalog gets wiped clean after every docker-compose down/up then is there a way I can "load" the catalog with iceberg tables that already exist in minio?

**Comment by dcarr178** [comment]
I poked around some more and saw sqlite files in the /tmp dir so I added a persistent volume to my docker-compose and this did the trick solving the problem for me.

docker-compose.yml
...
  iceberg:
    image: tabulario/iceberg-rest
    container_name: iceberg
    volumes:
      - ./tmp/volumes/iceberg:/tmp

**Comment by zxf1412** [comment]
after volume，can not run up
